version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/map"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/web-client"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/model"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
