backend:
  - functions/**/*

documentation:
  - docs/**/*
  - ./*.md

firebase-rules:
  - firebase/**/*

frontend:
  - volunteer-matcher/**/*

css:
  - ./**/*.css

map:
  - map/**/*

site:
  - site/**/*

security:
  - firebase/**/*

'mgmt / ops / product':
  - branding/**/*

'infra / devops':
  - .github/**/*
