files:
  - source: /map/src/i18n/langs/en.json
    translation: /map/src/i18n/langs/%locale%.json
  - source: /volunteer-matcher/src/translations/en.json
    translation: /volunteer-matcher/src/translations/%locale%.json
  - source: /site/src/locales/en-US.json
    translation: /site/src/locales/%locale%.json
