name: Sync Issues with ZenHub

on:
  schedule:
    - cron:  '0,20,40 * * * *'

jobs:
  sync-issues-with-zenhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Sync
      uses: ./.github/zenhub-issue-sync
      env:
        ZENHUB_TOKEN: ${{ secrets.ZENHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
